
from __future__ import annotations
import os
from datetime import datetime, timezone
import pandas as pd
from sqlalchemy import create_engine, text

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///paper_trading.db")
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)
engine = create_engine(DATABASE_URL, pool_pre_ping=True)

def init_db():
    with engine.begin() as con:
        con.execute(text("""
        CREATE TABLE IF NOT EXISTS signals (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            signal_date VARCHAR(20) NOT NULL,
            symbol VARCHAR(30) NOT NULL,
            name VARCHAR(200),
            price DOUBLE PRECISION, score DOUBLE PRECISION, signal VARCHAR(20),
            entry_low DOUBLE PRECISION, entry_high DOUBLE PRECISION, stop DOUBLE PRECISION,
            target1 DOUBLE PRECISION, target2 DOUBLE PRECISION, rsi DOUBLE PRECISION,
            rvol DOUBLE PRECISION, reasons TEXT,
            UNIQUE(signal_date, symbol)
        )""".replace("INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY","INTEGER PRIMARY KEY AUTOINCREMENT")
        if DATABASE_URL.startswith("sqlite") else """
        CREATE TABLE IF NOT EXISTS signals (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            signal_date VARCHAR(20) NOT NULL,
            symbol VARCHAR(30) NOT NULL,
            name VARCHAR(200),
            price DOUBLE PRECISION, score DOUBLE PRECISION, signal VARCHAR(20),
            entry_low DOUBLE PRECISION, entry_high DOUBLE PRECISION, stop DOUBLE PRECISION,
            target1 DOUBLE PRECISION, target2 DOUBLE PRECISION, rsi DOUBLE PRECISION,
            rvol DOUBLE PRECISION, reasons TEXT,
            UNIQUE(signal_date, symbol)
        )"""))
        con.execute(text("""
        CREATE TABLE IF NOT EXISTS paper_trades (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            opened_at VARCHAR(40) NOT NULL,
            symbol VARCHAR(30) NOT NULL, name VARCHAR(200),
            entry DOUBLE PRECISION NOT NULL, stop DOUBLE PRECISION NOT NULL,
            target1 DOUBLE PRECISION, target2 DOUBLE PRECISION,
            status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
            closed_at VARCHAR(40), exit DOUBLE PRECISION,
            pnl_pct DOUBLE PRECISION, outcome VARCHAR(100)
        )""" if DATABASE_URL.startswith("sqlite") else """
        CREATE TABLE IF NOT EXISTS paper_trades (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            opened_at VARCHAR(40) NOT NULL,
            symbol VARCHAR(30) NOT NULL, name VARCHAR(200),
            entry DOUBLE PRECISION NOT NULL, stop DOUBLE PRECISION NOT NULL,
            target1 DOUBLE PRECISION, target2 DOUBLE PRECISION,
            status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
            closed_at VARCHAR(40), exit DOUBLE PRECISION,
            pnl_pct DOUBLE PRECISION, outcome VARCHAR(100)
        )"""))

def save_signals(rows):
    if not rows: return
    init_db()
    with engine.begin() as con:
        for r in rows:
            con.execute(text("DELETE FROM signals WHERE signal_date=:d AND symbol=:s"), {"d":r["date"],"s":r["symbol"]})
            con.execute(text("""INSERT INTO signals
                (signal_date,symbol,name,price,score,signal,entry_low,entry_high,stop,target1,target2,rsi,rvol,reasons)
                VALUES (:date,:symbol,:name,:price,:score,:signal,:entry_low,:entry_high,:stop,:target1,:target2,:rsi,:rvol,:reasons)"""), r)

def get_signals(limit=1000, latest_only=False):
    init_db()
    q = "SELECT * FROM signals ORDER BY signal_date DESC, score DESC"
    df = pd.read_sql_query(text(q), engine)
    if latest_only and not df.empty:
        df = df[df.signal_date == df.signal_date.max()].copy()
    return df.head(limit)

def has_open_trade(symbol):
    init_db()
    with engine.connect() as con:
        return con.execute(text("SELECT COUNT(*) FROM paper_trades WHERE symbol=:s AND status='OPEN'"), {"s":symbol}).scalar() > 0

def open_trade(row):
    if has_open_trade(row["symbol"]): return False
    now = datetime.now(timezone.utc).isoformat()
    with engine.begin() as con:
        con.execute(text("""INSERT INTO paper_trades
        (opened_at,symbol,name,entry,stop,target1,target2,status)
        VALUES (:opened_at,:symbol,:name,:entry,:stop,:target1,:target2,'OPEN')"""),
        {"opened_at":now,"symbol":row["symbol"],"name":row.get("name"),"entry":row["price"],
         "stop":row["stop"],"target1":row["target1"],"target2":row["target2"]})
    return True

def get_trades():
    init_db()
    return pd.read_sql_query(text("SELECT * FROM paper_trades ORDER BY id DESC"), engine)

def close_trade(trade_id, exit_price, outcome):
    with engine.begin() as con:
        entry = con.execute(text("SELECT entry FROM paper_trades WHERE id=:id"), {"id":int(trade_id)}).scalar()
        if entry is None: return
        pnl = (float(exit_price)/float(entry)-1)*100
        con.execute(text("""UPDATE paper_trades SET status='CLOSED', closed_at=:closed,
        exit=:exit, pnl_pct=:pnl, outcome=:outcome WHERE id=:id"""),
        {"closed":datetime.now(timezone.utc).isoformat(),"exit":float(exit_price),"pnl":pnl,"outcome":outcome,"id":int(trade_id)})

def get_performance():
    t = get_trades()
    c = t[t.status=="CLOSED"].copy() if not t.empty else pd.DataFrame()
    if c.empty:
        return {"closed_trades":0,"wins":0,"losses":0,"win_rate":0.0,"avg_pnl":0.0,"total_return":0.0,"profit_factor":None}
    wins = c[c.pnl_pct>0]
    losses = c[c.pnl_pct<=0]
    gross_profit = wins.pnl_pct.sum()
    gross_loss = abs(losses.pnl_pct.sum())
    return {
        "closed_trades":len(c),"wins":len(wins),"losses":len(losses),
        "win_rate":100*len(wins)/len(c),"avg_pnl":float(c.pnl_pct.mean()),
        "total_return":float(((1+c.pnl_pct/100).prod()-1)*100),
        "profit_factor":float(gross_profit/gross_loss) if gross_loss>0 else None
    }
